<?php

namespace Database\Seeders;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            //ADMIN
            [
                'username' => 'admin',
                'password' => 'admin123',
                'email' => 'admin.klinik@vitaguard.com',
                'nomor_telepon' => '081234567890',
                'is_admin' => 1, //1 = Admin
                'member_id' => null,
                'dokter_id' => null,
            ],

            //PASIEN
            [
                'username' => 'uli_susanti',
                'password' =>  'Uli95',
                'email' => 'uli.susanti@gmail.com',
                'nomor_telepon' => '081234560001',
                'is_admin' => 0,
                'member_id' => 1,
                'dokter_id' => null,
            ],
            [
                'username' => 'keisha_jamalia',
                'password' =>  'Keisha97',
                'email' => 'keisha.jamalia@gmail.com',
                'nomor_telepon' => '081234560002',
                'is_admin' => 0,
                'member_id' => 2,
                'dokter_id' => null,
            ],
            [
                'username' => 'najam_ega',
                'password' =>  'Najam88',
                'email' => 'najam.ega@gmail.com',
                'nomor_telepon' => '081234560003',
                'is_admin' => 0,
                'member_id' => 3,
                'dokter_id' => null,
            ],
            [
                'username' => 'nova_wani',
                'password' =>  'Nova01',
                'email' => 'nova.wani@gmail.com',
                'nomor_telepon' => '081234560004',
                'is_admin' => 0,
                'member_id' => 4,
                'dokter_id' => null,
            ],
            [
                'username' => 'perkasa_harsaya',
                'password' =>  'Perkasa92',
                'email' => 'perkasa.harsaya@gmail.com',
                'nomor_telepon' => '081234560005',
                'is_admin' => 0,
                'member_id' => 5,
                'dokter_id' => null,
            ],
            [
                'username' => 'hendra_sihotang',
                'password' =>  'Hendra71',
                'email' => 'hendra.sihotang@gmail.com',
                'nomor_telepon' => '081234560006',
                'is_admin' => 0,
                'member_id' => 6,
                'dokter_id' => null,
            ],
            [
                'username' => 'paris_puspasari',
                'password' =>  'Paris79',
                'email' => 'paris.puspasari@gmail.com',
                'nomor_telepon' => '081234560007',
                'is_admin' => 0,
                'member_id' => 7,
                'dokter_id' => null,
            ],
            [
                'username' => 'rahmi_oliva',
                'password' =>  'Rahmi85',
                'email' => 'rahmi.oliva@gmail.com',
                'nomor_telepon' => '081234560008',
                'is_admin' => 0,
                'member_id' => 8,
                'dokter_id' => null,
            ],
            [
                'username' => 'olivia_zamira',
                'password' =>  'Olivia84',
                'email' => 'olivia.zamira@gmail.com',
                'nomor_telepon' => '081234560009',
                'is_admin' => 0,
                'member_id' => 9,
                'dokter_id' => null,
            ],
            [
                'username' => 'dewi_maimunah',
                'password' =>  'Dewi82',
                'email' => 'dewi.maimunah@gmail.com',
                'nomor_telepon' => '081234560010',
                'is_admin' => 0,
                'member_id' => 10,
                'dokter_id' => null,
            ],
            [
                'username' => 'uchita_ella',
                'password' =>  'Uchita82',
                'email' => 'uchita.ella@gmail.com',
                'nomor_telepon' => '081234560011',
                'is_admin' => 0,
                'member_id' => 11,
                'dokter_id' => null,
            ],
            [
                'username' => 'jamalia_carla',
                'password' =>  'Jamalia84',
                'email' => 'jamalia.carla@gmail.com',
                'nomor_telepon' => '081234560012',
                'is_admin' => 0,
                'member_id' => 12,
                'dokter_id' => null,
            ],
            [
                'username' => 'cinta_lili',
                'password' =>  'Cinta90',
                'email' => 'cinta.lili@gmail.com',
                'nomor_telepon' => '081234560013',
                'is_admin' => 0,
                'member_id' => 13,
                'dokter_id' => null,
            ],
            [
                'username' => 'nilam_titin',
                'password' =>  'Nilam07',
                'email' => 'nilam.titin@gmail.com',
                'nomor_telepon' => '081234560014',
                'is_admin' => 0,
                'member_id' => 14,
                'dokter_id' => null,
            ],
            [
                'username' => 'mustofa_firmansyah',
                'password' =>  'Mustofa07',
                'email' => 'mustofa.firmansyah@gmail.com',
                'nomor_telepon' => '081234560015',
                'is_admin' => 0,
                'member_id' => 15,
                'dokter_id' => null,
            ],
            [
                'username' => 'rangga_galur',
                'password' =>  'Rangga07',
                'email' => 'rangga.galur@gmail.com',
                'nomor_telepon' => '081234560016',
                'is_admin' => 0,
                'member_id' => 16,
                'dokter_id' => null,
            ],
            [
                'username' => 'sari_zulaika',
                'password' =>  'Sari',
                'email' => 'sari.zulaika@gmail.com',
                'nomor_telepon' => '081234560017',
                'is_admin' => 0,
                'member_id' => 17,
                'dokter_id' => null,
            ],
            [
                'username' => 'kamal_maras',
                'password' =>  'Kamal94',
                'email' => 'kamal.maras@gmail.com',
                'nomor_telepon' => '081234560018',
                'is_admin' => 0,
                'member_id' => 18,
                'dokter_id' => null,
            ],
            [
                'username' => 'kamila_citra',
                'password' => 'Kamila ',
                'email' => 'kamila.citra@gmail.com',
                'nomor_telepon' => '081234560019',
                'is_admin' => 0,
                'member_id' => 19,
                'dokter_id' => null,
            ],
            [
                'username' => 'melindaoktaviani',
                'password' => 'Melinda76',
                'email' => 'melinda@gmail.com',
                'nomor_telepon' => '081234560020',
                'is_admin' => 0,
                'member_id' => 20,
                'dokter_id' => null,
            ],

            //DOKTER
            [
                'username' => 'dr_kevin',
                'password' => 'Kevin3',
                'email' => 'kevin@vitaguard.com',
                'nomor_telepon' => '082100000001',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 1,
            ],
            [
                'username' => 'drg_rina',
                'password' => 'Rina6',
                'email' => 'rina@vitaguard.com',
                'nomor_telepon' => '082100000002',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 2,
            ],
            [
                'username' => 'dr_hendra',
                'password' => 'Hendra12',
                'email' => 'hendra@vitaguard.com',
                'nomor_telepon' => '082100000003',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 3,
            ],
            [
                'username' => 'dr_gita',
                'password' => 'Gita8',
                'email' => 'gita@vitaguard.com',
                'nomor_telepon' => '082100000004',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 4,
            ],
            [
                'username' => 'dr_ahmad',
                'password' => 'Ahmad15',
                'email' => 'ahmad@vitaguard.com',
                'nomor_telepon' => '082100000005',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 5,
            ],
            [
                'username' =>
                'dr_aditya', 'password' =>
                'Aditya1',
                'email' => 'aditya@vitaguard.com',
                'nomor_telepon' => '082100000006',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 6,
            ],
            [
                'username' => 'drg_antonius',
                'password' => 'Antonius9',
                'email' => 'antonius@vitaguard.com',
                'nomor_telepon' => '082100000007',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 7,
            ],
            [
                'username' => 'dr_lestari',
                'password' => 'Lestari5',
                'email' => 'lestari@vitaguard.com',
                'nomor_telepon' => '082100000008',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 8,
            ],
            [
                'username' => 'dr_maya',
                'password' => 'Maya11',
                'email' => 'maya@vitaguard.com',
                'nomor_telepon' => '082100000009',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 9,
            ],
            [
                'username' => 'dr_reza',
                'password' => 'Reza14',
                'email' => 'reza@vitaguard.com',
                'nomor_telepon' => '082100000010',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 10,
            ],
            [
                'username' => 'dr_sarah',
                'password' => 'Sarah4',
                'email' => 'sarah@vitaguard.com',
                'nomor_telepon' => '082100000011',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 11,
            ],
            [
                'username' => 'drg_clara',
                'password' => 'Clara2',
                'email' => 'clara@vitaguard.com',
                'nomor_telepon' => '082100000012',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 12,
            ],
            [
                'username' => 'dr_doni',
                'password' => 'Doni7',
                'email' => 'doni@vitaguard.com',
                'nomor_telepon' => '082100000013',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 13,
            ],
            [
                'username' => 'dr_dian',
                'password' => 'Dian16',
                'email' => 'dian@vitaguard.com',
                'nomor_telepon' => '082100000014',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 14,
            ],
            [
                'username' => 'dr_surya',
                'password' => 'Surya10',
                'email' => 'surya@vitaguard.com',
                'nomor_telepon' => '082100000015',
                'is_admin' => 0,
                'member_id' => null,
                'dokter_id' => 15,
            ],
        ];

        foreach ($data as $item) {
            User::create($item);
        }
    }
}
